#!/bin/bash

SBXIP="${SBXIP:-192.168.241.203}"
SBXROOT="${GITROOT:-/git}"
TIM='node /git/mantacode/srcrr-client/srcrr'

#'opencms-export' 'image-service' 
for i in 'nodejs-common-lib' 'core-app' 'community-app' 'www-411-app' 'manta-app-base-lib' 'rabbitmq-lib' 'kwtool-rules-lib' 'web-platform-lib'
do 
  echo $i;
  cd /git/$i;
  git checkout master;
  git pull;
  ${TIM} sync -s ${SBXIP}
  echo "--------------------------------------------------------------------------------"
done
