#!/usr/bin/perl
#
# A perl-5 script to see if an array element will change if 
# the variable assigned in a foreach is changed
#
$name = $0; $name =~ s'.*/''; # remove path--like basename
$usage = "usage:\n$name [-opt1] [-opt2] [-opt3]";

@a=('bob','joe','ken','scott','steve','gerry','barb');

print "foreach loop\n";
print "first pass (just printing the array):\n";
foreach $a (@a) {
  print "$a ";
}
print "\n\n";

print "change pass:\n";
foreach $a (@a) {
  if ($a=~/steve/) {
    $a=uc $a;
    print "$a changed";
  }
}
print "\n\n";

print "second pass (again just printing the array):\n";
foreach $a (@a) {
  print "$a ";
}
print "\n\n";

print "Now for a for loop\n";

@a=('bob','joe','ken','scott','steve','gerry','barb');

print "first pass (just printing the array):\n";
for ($a=$a[$i=0]; $i<=$#a; $a=$a[++$i]) {
  print "$a ";
}
print "\n\n";

print "change pass:\n";
for ($a=$a[$i=0]; $i<=$#a; $a=$a[++$i]) {
  if ($a=~/steve/) {
    $a=uc $a;
    print "$a changed";
  }
}
print "\n\n";

print "second pass (again just printing the array):\n";
for ($a=$a[$i=0]; $i<=$#a; $a=$a[++$i]) {
  print "$a ";
}
print "\n\n";

exit 0;

__END__
