#!/usr/bin/perl
#
# A perl-5 script to test regular exp.
#
$name = $0; $name =~ s'.*/''; # remove path--like basename
$usage = "usage:\n$name [-opt1] [-opt2] [-opt3]";

$prompt_string=
"Please input a regular expression in the form /regexp/ \n" .
  "or a string to test: ";

$regexp='^[.\s]+$';

print "We start with regexp '$regexp'\n";

print $prompt_string;
while (<>) {
  chomp;
  if ($_=~m,^/.*/$,) {
    ($regexp=$_)=~s,^/|/$,,g;
    print "Thank you, we have a new regexp '$regexp'\n";
  } else {
    if ($_=~/$regexp/) {
      print "'$_' did match the regexp '$regexp'\n";
    } else {
      print "'$_' did *NOT* match the regexp '$regexp'\n";
    }
  }
  print $prompt_string;
}

exit 0;

__END__
