#!/usr/bin/perl
#
# A perl script to test splice removal
#
$name = $0; $name =~ s'.*/''; # remove path--like basename
$usage = "usage:\n$name [-opt1] [-opt2] [-opt3]";

foreach $i ( 0 .. 10 ) {
  push(@a,sprintf("array_element%02d",$i));
}

# print "array 'a' has " . scalar(@a) . " elements in it.";

print join("\n",@a) . "\n\n";

$j=7;
print "Removing element with index $j\n\n";

splice(@a,$j,1);

print join("\n",@a) . "\n\n";

exit 0;

__END__
