#!/usr/bin/perl
#
# A perl-5 script to make a simple semaphore set with 10 flags.
#
$name = $0; $name =~ s'.*/''; # remove path--like basename
$usage = "usage:\n$name [-opt1] [-opt2] [-opt3]";

unshift(@INC,'.');
require "sem.pl";

use IPC::SysV qw(IPC_PRIVATE S_IRWXU IPC_CREAT);
use IPC::Semaphore;

$sem = new IPC::Semaphore($semkey, 10, S_IRWXU | IPC_CREAT);

exit 0;

__END__
