#!/usr/local/bin/perl
#
# A perl script to replace widget (default widget is an '~')
# with a linenumber
$name = $0;
$name =~ s'.*/''; # remove path--like basename
$usage = "usage:\n$name [-g] [-widget|-w # (~)] [-from|-f # (1)] [-by|-b #(1)]";

#   ***   Parse Command Line Argument(s)   ***
while ( @ARGV >= 1 ) {
  if    ( $ARGV[0] eq '-g' )  { $all='g'; shift; }
  elsif ( $ARGV[0] eq '-from'
        ||$ARGV[0] eq '-f' )  { $from = "$ARGV[1]";
 			          shift; shift; }
  elsif ( $ARGV[0] eq '-by'
        ||$ARGV[0] eq '-b' )  { $by = "$ARGV[1]";
 			          shift; shift; }
  elsif ( $ARGV[0] eq '-widget'
        ||$ARGV[0] eq '-w' )  { $widget = "$ARGV[1]";
 			          shift; shift; }
  elsif ( $ARGV[0] eq '-?' )  { do help($usage); }
  else { last; }
}  # end while

#   ***   Set defaults   ***
$by=1       if (!$by || $by !~/\d*/);
$from=1     if (!$from || $from !~/\d*/);
$widget='~' if (!$widget);

while (<>) {
  if 
}
