#!/usr/bin/perl
# A perl script to SCRIPT_DESCRIPTION

use strict;
use warnings;

my $name = $0;
my $name =~ s'.*/''; # remove path--like basename
my $usage = "usage:\n$name [-opt1] [-opt2] [-opt3]";

my $true=1; my $false=0;

exit 0;

__END__
