#!/usr/bin/perl
#
# A perl script to SCRIPT_DESCRIPTION
#
$name = $0;
$name =~ s'.*/''; # remove path--like basename
$usage = "usage:\n$name [-opt1] [-opt2] [-opt3]";

$true=1; $false=0;

exit 0;

__END__
