#!/usr/local/localadm/bin/perl
#!/usr/bin/perl

undef $/;			# process complete file
$_ = <>;

s'\$ 1S \$'<super>1</super>&Sgr;<super>+</super>'g;
s'\$ 3S \$'<super>3</super>&Sgr;<super>+</super>'g;

s'\$ 1P \$'<super>1</super>&Pgr;'g;
s'\$ 3P \$'<super>3</super>&Pgr;'g;

s'\$ 3D \$'<super>3</super>&Dgr;'g;
s'\$ 1D0\+ \$'<super>1</super>&Dgr;<sub>0+</sub>'g;
s'\$ 3D3 \$'<super>3</super>&Dgr;<sub>3</sub>'g;
s'\$ 3D2 \$'<super>3</super>&Dgr;<sub>2</sub>'g;
s'\$ 3D1 \$'<super>3</super>&Dgr;<sub>1</sub>'g;
s'\$ 1D2 \$'<super>1</super>&Dgr;<sub>2</sub>'g;

s'\$ o0\+ \$'&Ogr;<?Pub Fmt hardspace>=<?Pub Fmt hardspace>0<super>+</super>'g;
s'\$ o0- \$'&Ogr;<?Pub Fmt hardspace>=<?Pub Fmt hardspace>0<super>-</super>'g;
s'\$ o3 \$'&Ogr;<?Pub Fmt hardspace>=<?Pub Fmt hardspace>3'g;
s'\$ o2 \$'&Ogr;<?Pub Fmt hardspace>=<?Pub Fmt hardspace>2'g;
s'\$ o1 \$'&Ogr;<?Pub Fmt hardspace>=<?Pub Fmt hardspace>1'g;

s'\$ 3S1 \$'<super>3</super>&Sgr;<sub>1</sub><super>+</super>'g;
s'\$ 3P2 \$'<super>3</super>&Pgr;<sub>2</sub>'g;
s'\$ 3P1 \$'<super>3</super>&Pgr;<sub>1</sub>'g;
s'\$ 3P0- \$'<super>3</super>&Pgr;<sub>0<super>-</super></sub> }'g;
s'\$ 3P0\+ \$'<super>3</super>&Pgr;<sub>0<super>+</super></sub> }'g;
s'\$ 1P1 \$'<super>1</super>&Pgr;<sub>1</sub>'g;

s'\$ 1S0\+ \$'<super>1</super>&Sgr;<sub>0<super>+</super></sub>'g;
s'\$ 3S0- \$'<super>3</super>&Sgr;<sub>0<super>-</super></sub>'g;

s'\$ 3d10 \$'Cu<super>+</super><?Pub Fmt hardspace>3d<super>10</super><?Pub Fmt hardspace>F<super>-</super><?Pub Fmt hardspace>2p<super>6</super>'g;
s'\$ 3d94s \$'Cu<super>+</super><?Pub Fmt hardspace>3d<super>9</super> 4s<super>1</super><?Pub Fmt hardspace>F<super>-</super><?Pub Fmt hardspace>2p<super>6</super>'g;
s'\$ 3d104s \$'Cu<?Pub Fmt hardspace>3d <super>10</super> 4s<super>1</super><?Pub Fmt hardspace>F<?Pub Fmt hardspace>2p<super>5</super>'g;
s'\$ 3d94s2 \$'Cu<?Pub Fmt hardspace>3d <super>9</super> 4s<super>2</super><?Pub Fmt hardspace>F<?Pub Fmt hardspace>2p<super>5</super>'g;
s'\$ 3d104p \$'Cu<?Pub Fmt hardspace>3d <super>10</super> 4p<super>1</super><?Pub Fmt hardspace>F<?Pub Fmt hardspace>2p<super>5</super>'g;

s'\$ Re \$'R<sub>e</sub>'g;

s'SIGMA'&Sgr;'g;
s'PI'&Pgr;'g;
s'DELTA'&Dgr;'g;
s'LAMBDA'&Lgr;'g;
s'OMEGA'&Ogr;'g;


s'\$ Cu sup \+ \$'Cu<super>+</super>'g;
s'\$ F sup - \$'F<super>-</super>'g;
s'\$ F sub 2 \$'F<sub>2</sub>'g;

s| \\fI([^\\]*)\\fP|<italic> $1</italic>|g;
s| \\fB([^\\]*)\\fP|<bold> $1</bold>|g;

s|\~|<?Pub Fmt hardspace>|g;

print;
