#!/usr/local/localadm/bin/perl
#-----------------------------------------------------------------------------

#   ***   Define Strings, Values & Flags   ***
$name =~ s'.*/'';
$usage = "usage: $name [-l] [-n] [-f TERMCAP_file] [-e TERM ... ]\n";
$entry=0;
$explaination_flag=1;
$locate_only_flag=0;
$recursive_call=0;
$file_flag=1;
$explain="/home/parker/bin/termcaps/term.caps.4.1";
 $termcap_default="/usr/share/lib/termcap"; # for sparcs
#$termcap_default="/etc/termcap";           # for 3-50's

#   ***   Parse Command Line Argument(s)   ***
# while ( @ARGV > 1 && $ARGV[0] =~ /^-[^-]/ ) {
while ( @ARGV >= 1 ) {
  if ( $ARGV[0] eq '-e' ) {
    $entries[$entry++] = $ARGV[1];
    shift; shift;
    until ( $ARGV[0] =~ /^-[^-]/ || @ARGV == 0 ) { 
      $entries[$entry++] = $ARGV[0];
      shift;
    }  # end while
  } # end if 
  elsif ( $ARGV[0] eq '-f' ) {
    $termcap = $ARGV[1];
    shift; shift; }
  elsif ( $ARGV[0] eq '-n' ) { shift; $explaination_flag=0; }
  elsif ( $ARGV[0] eq '-l' ) { shift; $locate_only_flag=1; }
  elsif ( $ARGV[0] eq '-t' ) {
    shift;
    $recursive_call=1; }
  else { print "Illegal argument: \"$ARGV[0]\"\n"; die $usage; }
}  # end while

#   ***   Determine TERM Entry & TERMCAP File or Environment Variable   ***
if ( $entry == 0  )  { $entries[$entry]=$ENV{"TERM"}; }
if ( $termcap =~ "^$" )  { $termcap=$ENV{"TERMCAP"}; }
if ( $termcap =~ "^$" )  { # didn't find "TERMCAP" in environment
  $termcap=$termcap_default;
}
else { # DID find "TERMCAP" in environment
  if ( $termcap =~ /^\// ) { # TERMCAP was a path to a file
  }
  else { # TERMCAP was NOT a path to a file
  $file_flag=0;
  } # end if/else
} # end if/else

#   *** Report on planned activity   ***
print "Attempting to find $entries[0]";
if (@entries >1) {
  for ($entry=1; $entry<=($#entries-1); $entry++) {
  print ", $entries[$entry]";
  } # end for
print " & $entries[$#entries]";
} # end if
if ($file_flag) {
  print " in $termcap.\n";
}
else {
  print " in \$TERMCAP.\n";
}

#   ***   MAIN LOOP ON ENTRIES   ***
for ($entry=0; $entry<=$#entries; $entry++) {
#   ***   Find TERM Entry in TERMCAP   ***
$line=0;
if ($file_flag) {
  $found=0;                         # start search
  open(TERMCAP,"$termcap") || die("$0: cannot open $termcap file.\n");
  while(<TERMCAP>) {
    chop;
    if ($found) {
      $test=chop;                   # use $test later
      $entryline[$line++]=$_;       # makes end_point_inclusive
#     if ($_ =~ /[^\\]$/ ) {        # OLD test for 'OFF' condition
      if ("$test" ne "\\" ) {       # NEW test for 'OFF' condition
	$entryline[$line-1].=$test; # don't know what it was so put it back
	if ($locate_only_flag) { print $_.$test."\n"; }
	last;                       # terminates search after entry is found
        $found=0;
      } # end if
      if ($locate_only_flag) { print $_."\n"; }
    }
    else {
      if ($_ =~ /^[^\s#]*.*$entries[$entry]\|/) {   # test for 'ON' condition
	chop;
        $entryline[$line++]=$_; # makes begin_point_inclusive
        if ($locate_only_flag) { print $_."\n"; }
        $found=1;
      } # end if
    } # end if/else
  } # end while
  close(TERMCAP);
}
else { # TERMCAP contains entries
    $entryline[$line++]=$termcap;
} # end if/else

if ($locate_only_flag) { next; }

#   ***   Strip Seperate Capabilities and Sort Them   ***
$n=0; @caps=();
print $entryline[0] ."\n";
for ($lines=1; $lines<=$#entryline; $lines++)
{                                    # loop on entry lines
$entryline[$lines] =~ s/^[\s:]+//g;  # remove leading whitespace and :'s
$n += split(/:/,$entryline[$lines]); # split entry line on :'s
@caps=(@caps,@_);                    # add @_ to array @caps
} # end for on entry lines

$tc_flag=($caps[$#caps]=~/^tc=(.*)[:]?/); # set flag for for similar terminal entry
$tc_entry=$1;
@caps=sort(@caps);                    # sort array @caps

#   ***   Add Terminal Capability from Appropriate File   ***
if ($explaination_flag) {

# LOAD EXPLAIN ARRAY
  open(EXPLAIN,"$explain") || die("$0: cannot open $explain file.\n");
  while (<EXPLAIN>) {
    if ($_=~/^(..)\S*\s*/) {
      $explain{$1}=$';
    }
  } # end while
  close(EXPLAIN);

  for ($i=0; $i<=$#caps; $i++) {

# Don't bother adding explaination for duplicate entries.
if ( ($i>0) && ( "$cap" eq substr($caps[$i],0,2) ) ) { next; }

$cap=$caps[$i];      # copy cap
$cap=~s/^(..).*/\1/; # strip first two characters for cap search
$cap=~s/k[1-9]/k0/;  # change 'k' 1-9 to 'k0'
$cap=~s/l[1-9]/l0/;  # change 'l' 1-9 to 'l0'
$cap=~s/F[2-9]/F1/;  # change 'F' 2-9 to 'F1'
$cap=~s/F[B-Z]/FA/;  # change 'F' B-Z to 'FA'
$cap=~s/F[b-r]/Fa/;  # change 'F' b-r to 'Fa'
                     # these are special cases that are grouped in
                     # the the term.cap files for SunOS 3.5 and 4.1

# $maxlength=14 used in the two following lines
if (length($caps[$i])>14) { $caps[$i].="\n"; $caps[$i].= " " x 14 ; }
$caps[$i]=sprintf("%-14s %s", $caps[$i],$explain{$cap});
chop($caps[$i]);

  } # end for 
} # end if

if ($tc_flag) {
  print "Entry similar to $tc_entry\n";
  print "except for the following additions/changes:\n"; }

print join("\n",@caps)."\n";

if ($tc_flag && $explaination_flag) {
  print "\nNow for termcap entry $tc_entry\n" . "-" x 45 . "\n";
  print `$0 -e $tc_entry -f $termcap`;
} # end if

} # end for on entries

#   ***   EXIT GRACEFULLY   ***

# print  "All done.\007\n";
exit 0;

####   SUBROUTINES   ####
sub split_and_sort {
}

#  TIMING RESULTS 
# time tc.work -e vt100
# yielded 
#  0.7 real  0.5 user 0.2 sys <- explainations stored in an associative array
# 15.0 real 14.2 user 0.4 sys <- generated for each entry by perl
# 17.0 real  2.1 user 6.8 sys <- generated for each entry by `grep|cut`
