#!/usr/bin/perl
#
# A perl-5 script to test various loop structures
#
$name = $0; $name =~ s'.*/''; # remove path--like basename
$usage = "usage:\n$name";

print "While loop:\n";
  $i=0;
  while ( $i<10 ) {
    printf "%2d ", $i++;
  }
  print "\n----------------------------\n";

print "\$i starts at 10 in  while (\$i<10) { loop } (showing check is before execution, loop is never executed):\n";
  $i=10;
  while ( $i<10 ) {
    printf "%2d ", $i++;
  }
  print "\n----------------------------\n";

print "\$i starts at 0 Do {} Until (\$i>9) loop:\n";
  $i=0;
  do {
    printf "%2d ", $i++;
  } until ($i>9);
  print "\n----------------------------\n";

print "\$i starts at 10 in  do { loop } (\$i<10) (showing that check is after execution, guarantying one execution):\n";
  $i=10;
  do {
    printf "%2d ", $i++;
  } until ($i>9);
  print "\n----------------------------\n";

print "Foreach ( 0 .. 9 ) loop:\n";
  foreach $i ( 0 .. 9 ) { $array[$i]="$i is a number"; }
  foreach $i ( 0 .. 9 ) { print "$array[$i]\n"; }
  print "\n----------------------------\n";

print "For loop [ for (\$i=0; \$i<10; \$i++) { ... } ] :\n";
  for ($i=0; $i<10; $i++) {
    print "'$i' ";
  }
  print "\n----------------------------\n";

print "\$i starts at 10 For loop with end condition (\$i<10) :\n";
  for ($i=10; $i<10; $i++) {
    print "'$i' ";
  }
  print "\n----------------------------\n";


exit 0;

__END__
